services:

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: cursos-backend-develop
    restart: unless-stopped
    ports:
      - "3009:3000"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - sqlite_data_develop:/app/data
      - uploads_data_develop:/app/uploads
    networks:
      - app-network-develop

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: cursos-frontend-develop
    restart: unless-stopped
    ports:
      - "8089:80"
    depends_on:
      - backend
    networks:
      - app-network-develop

volumes:
  sqlite_data_develop:
  uploads_data_develop:

networks:
  app-network-develop:
    driver: bridge